language: node_js
node_js:
  - '8'
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  - provider: npm
  - email: "michael.turnwall@mirumagency.com"
  - on:
      - branch: master
after_deploy:
  - snyk monitor
